FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY Clients/ ./Clients/
COPY common/ ./common/
RUN go build -o client ./Clients

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/client .
CMD ["./client"]